server:
  port: 8091

spring:
  application:
    name: movie-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_theater?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.kgc.project.common.entity

logging:
  level:
    cn.kgc.movie.server.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


#\u81EA\u5B9A\u4E49\u53D8\u91CF
movie:
  page:
    size: 8

