#\u6B64\u6587\u4EF6\u7F16\u7801\u4E3AUTF-8
server:
  port: 8092

spring:
  application:
    name: cinema-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_theater?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  type-aliases-package: cn.kgc.project.common.entity

logging:
  level:
    cn.kgc.cinema.server.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


#\u81EA\u5B9A\u4E49\u53D8\u91CF
article:
  page:
    size: 10


